### ISSUE TITLE
The blackjack rules are too simple

### ISSUE THREAD

**Issue by mekolat** [themanaworld/tmwa-server-data#194]
It doesn't even handle a tie properly
IMO we should use this flowchart: http://code.dawnofthegeeks.com/2009/04/30/blackjack-lesson-2-the-flowchart/

**Comment by nashley** [comment]
@mekolat I agree that it's too simple, but does anyone use it? It should be more rewarding in some way. Perhaps the casino coins could be turned in for special items instead of just GP.

**Comment by mekolat** [comment]
hm it looks like the website has a problem so here's the patent: https://www.google.com/patents/US20080067747
