### ISSUE TITLE
Fight club spamming GM log

### ISSUE THREAD

**Issue by Cassy1** [themanaworld/tmwa-server-data#228]
@mekolat I keep on missing you on IRC so let's try it this way:
Please check this http://server.themanaworld.org/gm/gm.log.2014-11
There are douzands, maybe over 100 lines spamming the GM log with "@killer" , "@killable" and "@alive"

**Comment by wushin** [comment]
@Cassy1 should be fixed in recent versions

**Comment by mekolat** [comment]
not just should; we removed the `gmcommand` builtin
