### ISSUE TITLE
Convert Functioned NPCs

### ISSUE THREAD

**Issue by wushin** [themanaworld/tmwa-server-data#311]
Make generic function NPCs part of tiled map data.

**Comment by wushin** [comment]
@mekolat

**Comment by mekolat** [comment]
you mean add "NPC" type objects and put a "callfunc" property?

**Comment by wushin** [comment]
009-2,65,49,0|shop|Barkeeper|112,Beer:*1,Cake:*1,Steak:*1
^ Could be parsed same as warp + sprite_id & Shopping_list
So TMX would have the same info as a warp plus Item1, Item2, Item3 etc.

-AND-

Stuffs like 
009-2,50,48,0|script|Receptionist#inn|108
{
    set @npcname$, "Receptionist";
    set @cost, 100;
    callfunc "Inn";
    end;
}

Similiar to how we process out mobs and warps now.

**Comment by mekolat** [comment]
hm, so for that receptionist I would add a new object, set its type to NPC, name it Receptionist#inn and then I would add properties:
* callfunc => Inn

then tmx_rasterizer would automatically add the @npcname$ variable which would be explode(objectName, "#")[0] then it would treat all the object properties as builtins

**Comment by wushin** [comment]
Nah, make vars @ like normal
So @cost is the var name and 100 is the value

**Comment by wushin** [comment]
as for debug yeah we can do a debug macro

**Comment by mekolat** [comment]
@Cassy1 @wushin see proposal on https://www.themanaworld.org/index.php/User:Meko/Tiled/NPC_Proposal

**Comment by mekolat** [comment]
@Cassy1 here is a demo of the proposal: https://github.com/themanaworld/tmwa-client-data/pull/248
(still waiting for your opinion)

**Comment by wushin** [comment]
Make shops type shop instead of npc. It makes output of files easier to deal with.

**Comment by mekolat** [comment]
@wushin ok
