### ISSUE TITLE
Add daily quests to quest log

### ISSUE THREAD

**Issue by mekolat** [themanaworld/tmwa-server-data#408]
In `OnPCLoginEvent` check if daily quests are available and if yes then update the quest state

**Comment by Rawng** [comment]
handle case where quest becomes available while player is logged in

**Comment by mekolat** [comment]
@Rawng can't do that unless we add a timer

**Comment by Rawng** [comment]
seems like a bad player experience to require relogging. what about checking with an NPC?

**Comment by mekolat** [comment]
it would just update the quest log; the player would NOT have to re-login to do the quest; it would work just like it always had
