### ISSUE TITLE
Getting on the ferry after it left

### ISSUE THREAD

**Issue by mekolat** [themanaworld/tmwa-server-data#424]
If you click on the ferry to open a dialog window and the ferry leaves you can still get on the ferry after it's gone. We need to add a check

**Comment by nashley** [comment]
[Relevant file](https://github.com/themanaworld/tmwa-server-data/blob/9a022915b5a3415c342284ba4c925f85b4c6bd99/world/map/npc/functions/ferry.txt#L104).

**Comment by nashley** [comment]
Is this still reproducable? I can't seem to get a dialog box to open. It either says to move closer or puts me on the ferry immediately.
