### ISSUE TITLE
Problem with operator minus (-) in magic scripts

### ISSUE THREAD

**Issue by monwarez** [themanaworld/tmwa-server-data#454]
I am trying to have a local server for testing purpose, but I have issue with magic.
In fact for every files who contain (- a b) fails the parse (if I replace - by + it's work).
For example with the file: world/map/conf/magic-procedures.sex
5:7 error: parser gave up before end of file
                                  (- school MAGIC)
 5:7: error: next token: TOKEN 'school'

I use FreeBSD 10.2-STABLE on amd64
And building on the master branch of the server(maybe the build was done with clang).

**Comment by mekolat** [comment]
@monwarez please paste your full code (the content of `(SPELL)`)

**Comment by monwarez** [comment]
(PROCEDURE default_effect ()
    (sfx caster
        (+
            (- school MAGIC)
            2)
        0))

**Comment by mekolat** [comment]
the correct code would be
```lisp
(PROCEDURE default_effect (school)
    (sfx caster
        (+
            (- school MAGIC)
            2)
        0))
```
(you need to define `school`)

**Comment by mekolat** [comment]
@monwarez please tell me if I can close this issue

**Comment by monwarez** [comment]
I try it but get the same error

**Comment by monwarez** [comment]
Yes you can close this issue, I will check the code to see why it's not working.

**Comment by mekolat** [comment]
@monwarez when you call it you need to call with an argument too.

define:
```lisp
(PROCEDURE default_effect (school)
    (sfx caster
        (+
            (- school MAGIC)
            2)
        0))
```


call:
```lisp
(CALL default_effect school)
```
(here `school` can be any number or variable)

**Comment by mekolat** [comment]
@monwarez I just noticed the code you sent is directly taken from `magic_procedures.sex` but yet for tmw and on my local server it works just fine. Are you perhaps using TMWA on FreeBSD?

**Comment by monwarez** [comment]
Yes I use TMWA on FreeBSD. This files are for tmw not tmwa ?

**Comment by mekolat** [comment]
No idea what you mean by "tmw not tmwa". Anything that is in `tmwa-server-data` is parsed by tmwAthena while things that are in `tmwa-client-data` are parsed by the client

**Comment by monwarez** [comment]
Never mind, I thought there were two versions of the server. So do you thinks it is relative to FreeBSD ?

**Comment by mekolat** [comment]
@monwarez I have no idea. You should try to fix the [errors](https://s3.amazonaws.com/archive.travis-ci.org/jobs/100064028/log.txt) reported by Travis-CI

**Comment by monwarez** [comment]
I will look at the log, maybe I will find a solution

**Comment by mekolat** [comment]
### conversation moved here: https://github.com/themanaworld/tmwa/pull/189
