### ISSUE TITLE
Dying on a PvP map returns you to Soul Menhir

### ISSUE THREAD

**Issue by wushin** [themanaworld/tmwa-server-data#478]

**Comment by mekolat** [comment]
and what is the expected/wanted behaviour?

**Comment by wushin** [comment]
go @die on 012-4 one would expect resave to be used, but it;'s ignored.

**Comment by mekolat** [comment]
that whole block in pc.cpp should be removed: https://github.com/themanaworld/tmwa/blob/master/src/map/pc.cpp#L3334
`if (sd->bl_m->flag.get(MapFlag::PVP) && !battle_config.pk_mode)`

**Comment by wushin** [comment]
@mekolat you wanna do it or should I?

**Comment by mekolat** [comment]
@wushin do it and make sure to put `closes themanaworld/tmwa-server-data#478` in the body of the commit message
